skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pool_tmp = "B63BKUN46hSJzRqEw72GLw3TWW1eKCdzpyDWiPSsMooz"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=f2ad3123-e8a9-44b7-a393-6c53cede5e6d"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
